Fix ETH estimation gas price
Appscrunch/Multy-back pull request #132
Opened 2019-01-04 16:19 UTC by PashaKlybik

2019-01-05 11:27 UTC, Enmk requested changes
Please fix issues highlighted, and please add meaningful commit description.

2019-01-05 11:27 UTC, Enmk commented on client/rest.go
> +func fetchMempool(loger slf.StructuredLogger, mempool *sync.Map) EstimationSpeeds {
This method is a good candidate for adding some unit-test, please do so. You need to cover few cases here:
* many records (>1500)
* few records (<1300)
* no recors at all.

Also, method name is quite misleading, it should be something like `estimateTransactionGasPrice`

2019-01-05 11:27 UTC, Enmk commented on client/rest.go
> +	//TODO remove after testing this logs
I guess you should remove this...

2019-01-05 11:27 UTC, Enmk commented on client/rest.go
> +func checkAddressIsConstact(loger slf.StructuredLogger, client ethpb.NodeCommunicationsClient, address string) int32 {
Please do not pass logger here (and other functions too), since this is a gas price estimation fix. We should add another task for messing with logs.

2019-01-08 08:33 UTC, nickpro commented on client/rest.go
> +func checkAddressIsConstact(loger slf.StructuredLogger, client ethpb.NodeCommunicationsClient, address string) int32 {
seems func name is named with an error

2019-01-08 08:35 UTC, nickpro commented on client/rest.go
> +	if len(fees) > 1300 {
what does magic number 1300 means? please, leave a comment or use constant

2019-01-09 13:51 UTC, Enmk approved these changes
Ok

2019-01-09 13:52 UTC, merged