Run dev environment
Appscrunch/Multy-back pull request #136
Opened 2019-01-29 11:08 UTC by PashaKlybik

Update vendor for fix bug with conection to BTC NODE
wrong read from configuration file
fix connection ns-eth to eth node on local machine 
fix wrong certificate signed by unknown authority on docker conteiner
fix panica after wrong response on resync ns-btc

2019-01-29 11:14 UTC, nickpro submitted a review, later dismissed

2019-01-29 11:24 UTC, Enmk requested changes
Mostly Ok, please fix highlighted issues and update vendored btcdsuite properly with:
```
govendor fetch github.com/btcsuite/btcd
```

Also please update existing docker-compose.yml (all secrets should be provided via env-variables and/or config files)

2019-01-29 11:24 UTC, Enmk commented on ns-btc/server.go
> +			return nil, fmt.Errorf("EventResyncAddress: request.Get : %v", errs)
Please use `errors.Wrapf(err, "%s Request failed", url)` here

https://godoc.org/github.com/pkg/errors

2019-01-29 11:24 UTC, Enmk commented on ns-eth/eth.go
> +	WsOrigin string
Please add a comment here:
```// Overrides WS origin if non-empty.```

2019-01-31 04:52 UTC, Enmk commented on multy-back.go
> +		if len(usersContracts) == 0 {
Why this ?

2019-01-31 05:49 UTC, PashaKlybik commented on multy-back.go
> +		if len(usersContracts) == 0 {
Typo when copying was here.

2019-01-31 08:02 UTC, Enmk commented on .gitignore
> +*/*.log
`*/**/*.log` matches all .log files, no matter how deep

2019-01-31 08:48 UTC, Enmk approved these changes
Ok

2019-01-31 08:48 UTC, Enmk commented on .gitignore
> +cmd/currencies
Is that a directory with config files ?

2019-01-31 08:48 UTC, merged