Move logic with ETH mempool from multy-back to ns-eth
Appscrunch/Multy-back pull request #139
Opened 2019-02-15 15:38 UTC by PashaKlybik

Reload mempool from geth evry 20 block
Move estimateTransactionGasPrice to eth node service

2019-02-15 15:49 UTC, nickpro commented on eth/handlers.go
> +				// WHAT THIS?
you serious?

2019-02-15 15:59 UTC, nickpro commented on ns-eth/txpool.go
> +	if len(fees) > 500 {
please, leave comments near magic numbers like 500 or 1300

2019-02-18 11:17 UTC, Enmk requested changes
Minor modifications required

2019-02-18 11:17 UTC, Enmk commented on ns-eth-protobuf/streamer.proto
> +message EstimateGasPrice {
Please rename to `GasPriceEstimation`

2019-02-18 11:17 UTC, Enmk commented on ns-eth/block.go
> +	if (c.LastBaseBlock + 20) < block.Number {
Please make `20` a named variable or even a config option.

2019-02-20 10:02 UTC, Enmk requested changes
Some modifications still required

2019-02-20 10:02 UTC, Enmk commented on client/rest.go
> +			var gasPriceEstimates *ethpb.GasPriceEstimation
`gasPriceEstimate` or `gasPriceEstimation`...

2019-02-20 10:02 UTC, Enmk commented on config.go
> +	ETHDefaultGasPrice store.GasPriceEstimation
Please update example config too.

2019-02-20 10:02 UTC, Enmk commented on ns-btc-protobuf/streamer.pb.go
> -const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package
Please remove that change from PR

2019-02-20 10:02 UTC, Enmk commented on ns-eth/txpool.go
> +	"pending": {
This could be as simple as that:
```
		"pending": {
			"0x00000000C0293c8cA34Dac9BCC0F953532D34e4d": { //address
				"685615": { // nonce
					... // transaction body, see RPCTransaction for details
				}
			}
		},
		"queued": {
			// same as for "pending"
               }
```

2019-02-20 10:02 UTC, Enmk commented on ns-eth/txpool.go
> +	// we go on all addresses and find transaction with minimum  nonce
// For each address, find a transaction with smaller nonce, filtering out txs with nonce ridiculously large

2019-02-20 10:02 UTC, Enmk commented on ns-eth/txpool.go
> +		var nonce_str string = ""
`nonce_min_str`

2019-02-20 10:02 UTC, Enmk commented on ns-eth/txpool.go
> +func (c *Client) EstimateTransactionGasPrice() *pb.GasPriceEstimation {
Please return `TransactionFeeRateEstimation` here, and get rid of protobuf import

2019-02-20 12:45 UTC, Enmk approved these changes
Ok

2019-02-20 12:47 UTC, merged